include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    depend_on_referenced_packages: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_is_empty: ignore
